/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Accelerator models
 * Environment: Production
 * Environment Id: 77004149-9b3a-01e8-f362-d776466d4545
 */
export const assetFolders = {
    /**
     * Accelerator exports
     */
    acceleratorExports: {
        id: 'f56f3e01-834f-441f-bc95-44aac2f05409',
        name: 'Accelerator exports',
        externalId: undefined,
        folders: {}
    }
} as const;
