/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Accelerator models
 * Environment: Production
 * Environment Id: 77004149-9b3a-01e8-f362-d776466d4545
 */
export const contentTypes = {
    /**
     * Accelerator Model
     */
    accelerator_model: {
        codename: 'accelerator_model',
        id: '007ace2d-d752-4d54-a3a3-c9168f7f4e1e',
        externalId: undefined,
        name: 'Accelerator Model',
        elements: {
            /**
             * Export data (asset)
             */
            export_data: {
                codename: 'export_data',
                id: '1492cbca-66d7-4b7e-8a54-ccade73cbc51',
                externalId: undefined,
                name: 'Export data',
                required: true,
                type: 'asset'
            }
        }
    }
} as const;
