/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Accelerator models
 * Environment: Production
 * Environment Id: 77004149-9b3a-01e8-f362-d776466d4545
 */
export const languages = {
    /**
     * Default project language
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        isActive: true,
        isDefault: true,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'Default project language'
    }
} as const;
