/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Project name: Accelerator models
 * Environment: Production
 * Environment Id: 77004149-9b3a-01e8-f362-d776466d4545
 */
export const taxonomies = {} as const;
