import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Accelerator Model
 * Id: 007ace2d-d752-4d54-a3a3-c9168f7f4e1e
 * Codename: accelerator_model
 */
export type AcceleratorModel = IContentItem<{
    /**
     * Export data (asset)
     * Required: true
     * Id: 1492cbca-66d7-4b7e-8a54-ccade73cbc51
     * Codename: export_data
     */
    export_data: Elements.AssetsElement;
}>;
